name: domain
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.7.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  dartz: 0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.2
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0